Make Exception picklable
There is a bug in pickle [1], due to which it cannot dump Exception
subclasses with different super() args:

Simple reproducer:

    In [29]: import clickhouse_driver.errors as err

    In [30]: pickle.loads(pickle.dumps(err.ServerException(message='foo', code=1, nested=Exception('foo'))))
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-30-6d4a4869bbeb> in <module>
    ----> 1 pickle.loads(pickle.dumps(err.ServerException(message='foo', code=1, nested=Exception('foo'))))

    TypeError: __init__() missing 2 required positional arguments: 'message' and 'code'

  [1]: https://bugs.python.org/issue37287